name: Nuget Component Publish

on:
  push:
    branches:
      - master

jobs:
  update-nuget-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-setup-dotnet@v1
      - uses: actions/setup-gitversion@v1.0.0
      - run: GitVersion
