name: Nuget Component Publish

on:
  push:
    tags:
      - '*'
    branches:
      - develop

jobs:
  update-nuget-config:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:PackageVersion=${{ steps.gitversion.outputs.semVer }}

    - name: Test
      run: dotnet test --no-restore --collect:"XPlat Code Coverage"

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: '**/TestResults/**/coverage.cobertura.xml'
        badge: true
        format: 'markdown'
        output: 'both'
        thresholds: '70 90'
        fail_below_min: true

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.semVer }} Thunderquack.Huification/Thunderquack.Huification.csproj

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --symbol-source https://nuget.smbsrc.net